### ISSUE TITLE
The audio dataset

### ISSUE THREAD

**Issue by 12yaya** [saehanjo/thalamusdb#1]
Hello, I see that your paper says that the audio dataset has eleven columns, but I only see 10 columns in the csv file here, there is no AudioClip column, why is that? Can you upload the full csv file if it is convenient? Thanks

**Comment by saehanjo** [comment]
Hello, thank you for reaching out! Please find the csv file with the added column (audio_clip) here:
[youtube_audios.csv](https://github.com/user-attachments/files/16325744/youtube_audios.csv)
